In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
def duration(data):
    # duration in minutes 
    total_duration = (data.iloc[-1, :].time_second - data.iloc[0, :].time_first) / 60

    # how much of that was break time?
    # how long from the last trial in one block to the first trial in the next block?
    break_times = []
    for i in range(len(data)-1):
        if data.iloc[i, :].block != data.iloc[i+1, :].block:
            break_time = data.iloc[i+1, :].time_first - data.iloc[i, :].time_second
            break_times.append(break_time)


    break_time = sum(break_times) / 60  # in minutes
    active_time = total_duration - break_time

    print(f"Total duration: {total_duration:.2f} minutes")
    print(f"Break time: {break_time:.2f} minutes") # talked a lot with line hehe
    print(f"Active time: {active_time:.2f} minutes")
    print(f"Active time per block: {active_time / data['block'].nunique():.2f} minutes")


def duration_estimation(n_blocks, n_events_per_block, ISI, rng_interval, avg_response_time=0.5):
    # estimated duration in minutes
    avg_rng = sum(rng_interval) / 2
    estimated_duration = n_blocks * (n_events_per_block * (ISI + avg_rng + avg_response_time) ) / 60
    print(f"Estimated duration: {estimated_duration:.2f} minutes")

# ISI = 0.54

In [24]:
data = pd.read_csv("../output/ExpectingCerebellOPM/test_laura_3.4_isi-54.csv")

# count how many of each combination of stim_site_first, stim_site_second, repeated, expected in the data
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).size().reset_index(name='counts')

  stim_site_first stim_site_second    repeated    expected  counts
0           index            index    repeated    expected      74
1           index            index    repeated  unexpected      24
2           index           middle  unrepeated    expected      74
3           index           middle  unrepeated  unexpected      24
4          middle            index  unrepeated    expected      74
5          middle            index  unrepeated  unexpected      24
6          middle           middle    repeated    expected      74
7          middle           middle    repeated  unexpected      24

In [25]:
# reaction time for the different conditions
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).agg({'RT': ['mean', 'std']}).sort_values(by=('RT', 'mean'))

                                                              RT
                                                            mean       std
stim_site_first stim_site_second repeated   expected
index           index            repeated   expected    0.372143  0.098801
middle          middle           repeated   unexpected  0.402150  0.094005
index           middle           unrepeated unexpected  0.421644  0.088765
middle          middle           repeated   expected    0.449498  0.183758
index           middle           unrepeated expected    0.466487  0.078255
middle          index            unrepeated expected    0.478485  0.109597
                                            unexpected  0.548771  0.106932
index           index            repeated   unexpected  0.556606  0.339432

In [26]:
duration(data)

Total duration: 29.56 minutes
Break time: 14.71 minutes
Active time: 14.85 minutes
Active time per block: 3.71 minutes

# ISI = 0.71


Seems like the larger ISI gives more difference between expected and unexpected conditions in terms of reaction time. Could also be a result of having more trials

In [27]:
data = pd.read_csv("../output/ExpectingCerebellOPM/test_laura_3.5_isi-71.csv")

# count how many of each combination of stim_site_first, stim_site_second, repeated, expected in the data
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).size().reset_index(name='counts')


# count how many of each combination of stim_site_first, stim_site_second, repeated, expected in the data
#data.groupby(["repeated", "expected"]).size().reset_index(name='counts')

  stim_site_first stim_site_second    repeated    expected  counts
0           index            index    repeated    expected     114
1           index            index    repeated  unexpected      38
2           index           middle  unrepeated    expected     114
3           index           middle  unrepeated  unexpected      38
4          middle            index  unrepeated    expected     114
5          middle            index  unrepeated  unexpected      38
6          middle           middle    repeated    expected     114
7          middle           middle    repeated  unexpected      38

In [28]:
# reaction time for the different conditions
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).agg({'RT': ['mean', 'std']}).sort_values(by=('RT', 'mean'))

                                                              RT
                                                            mean       std
stim_site_first stim_site_second repeated   expected
middle          middle           repeated   expected    0.398119  0.109750
index           index            repeated   expected    0.403597  0.102650
middle          index            unrepeated expected    0.442500  0.175341
index           middle           unrepeated expected    0.449569  0.190774
                index            repeated   unexpected  0.463170  0.099950
middle          index            unrepeated unexpected  0.480400  0.156629
index           middle           unrepeated unexpected  0.485098  0.102039
middle          middle           repeated   unexpected  0.513892  0.251508

In [29]:
duration(data)

Total duration: 31.07 minutes
Break time: 6.17 minutes
Active time: 24.90 minutes
Active time per block: 6.23 minutes

# ISI = 0.67

ISI=0.67,
 
n_events_per_block = 160,

rng_interval =  (0.75, 1.0),

In [30]:
data = pd.read_csv("../output/ExpectingCerebellOPM/test_laura_3.6.csv")

# count how many of each combination of stim_site_first, stim_site_second, repeated, expected in the data
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).size().reset_index(name='counts')

#duration(data)

  stim_site_first stim_site_second    repeated    expected  counts
0           index            index    repeated  unexpected      21
1           index           middle  unrepeated    expected      61
2          middle            index  unrepeated  unexpected      21
3          middle           middle    repeated    expected      61

In [31]:
avg_response_time = 0.9#data['RT'].mean()
print(f"Average response time: {avg_response_time:.2f} seconds")


duration_estimation(n_blocks=4, n_events_per_block=160, ISI=0.71, rng_interval=(1., 1.25), avg_response_time=avg_response_time)

Average response time: 0.90 seconds
Estimated duration: 29.17 minutes

In [32]:


data = pd.read_csv("../output/ExpectingCerebellOPM/lau_m_behavioural_test_3.8.csv")

# count how many of each combination of stim_site_first, stim_site_second, repeated, expected in the data
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).size().reset_index(name='counts')

  stim_site_first stim_site_second    repeated    expected  counts
0           index            index    repeated    expected     128
1           index            index    repeated  unexpected      44
2           index           middle  unrepeated    expected     128
3           index           middle  unrepeated  unexpected      44
4          middle            index  unrepeated    expected     128
5          middle            index  unrepeated  unexpected      44
6          middle           middle    repeated    expected     128
7          middle           middle    repeated  unexpected      44

In [33]:
# reaction time for the different conditions
data.groupby(["stim_site_first", "stim_site_second", "repeated", "expected"]).agg({'RT': ['mean', 'std']}).sort_values(by=('RT', 'mean'))

                                                              RT
                                                            mean       std
stim_site_first stim_site_second repeated   expected
index           index            repeated   expected    0.617243  0.165367
middle          middle           repeated   unexpected  0.679327  0.101736
index           index            repeated   unexpected  0.703824  0.293929
middle          index            unrepeated expected    0.823812  0.281485
                middle           repeated   expected    0.829280  0.356602
index           middle           unrepeated unexpected  0.870073  0.233366
middle          index            unrepeated unexpected  0.905168  0.273937
index           middle           unrepeated expected    1.010157  0.376277

In [34]:
data.agg({'RT': ['mean', 'std']})

            RT
mean  0.812154
std   0.317244

In [35]:
duration(data)

Total duration: 37.86 minutes
Break time: 7.57 minutes
Active time: 30.30 minutes
Active time per block: 7.57 minutes

In [36]:
sum([1 for correct in data["correct"] if correct])/len(data)  # overall accuracy

0.8313953488372093

# Check that motor preparation is balanced across conditions

In [3]:
conditions = pd.DataFrame()

for finger1 in ["index", "middle"]:
    for rep in ["repeated", "unrepeated"]:
        finger2 = finger1 if rep == "repeated" else ("middle" if finger1 == "index" else "index")
        for exp in ["expected", "unexpected"]:
            
            motor_prep = finger2 if exp == "expected" else ("middle" if finger2 == "index" else "index") 
            # do something

            tmp_data = {
                "finger1": finger1,
                "finger2": finger2,
                "rep": rep,
                "exp": exp,
                "motor_prep": motor_prep
            }
            conditions = pd.concat([conditions, pd.DataFrame([tmp_data])], ignore_index=True)

In [4]:
conditions

  finger1 finger2         rep         exp motor_prep
0   index   index    repeated    expected      index
1   index   index    repeated  unexpected     middle
2   index  middle  unrepeated    expected     middle
3   index  middle  unrepeated  unexpected      index
4  middle  middle    repeated    expected     middle
5  middle  middle    repeated  unexpected      index
6  middle   index  unrepeated    expected      index
7  middle   index  unrepeated  unexpected     middle

if we want to compare expected vs unexpected trials do we have equal trials with motor preparation for index and middle finger? and if we want to compare rep vs non rep trials do we have equal trials with motor preparation for index and middle finger?

*Note:* one could argue that after the second stimulus there is a difference between expected and unexpected trials in terms of motor preparation, since in unexpected trials the participant needs to change their prepared response. We can potentially argue that the motor preparation and stimulus response should happen in the two different hemispheres (stimulus is presented to the left hand, response with the right hand), but still something to consider.

In [ ]:
print("\nMotor preparation counts for expected vs unexpected trials:")
print(conditions.groupby("exp")["motor_prep"].value_counts())

print("\nMotor preparation counts for repeated vs non-repeated trials:")
print(conditions.groupby("rep")["motor_prep"].value_counts())

print(conditions.groupby(["exp","rep"])["motor_prep"].value_counts())

Motor preparation counts for expected vs unexpected trials:
exp         motor_prep
expected    index         2
            middle        2
unexpected  index         2
            middle        2
Name: count, dtype: int64

Motor preparation counts for repeated vs non-repeated trials:
rep         motor_prep
repeated    index         2
            middle        2
unrepeated  index         2
            middle        2
Name: count, dtype: int64
exp         rep         motor_prep
expected    repeated    index         1
                        middle        1
            unrepeated  index         1
                        middle        1
unexpected  repeated    index         1
                        middle        1
            unrepeated  index         1
                        middle        1
Name: count, dtype: int64

rep         motor_prep
repeated    index         2
            middle        2
unrepeated  index         2
            middle        2
Name: count, dtype: int64